name: adventure_dice_roller
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

dependencies:
  args: ^2.4.0
  dotenv: ^4.2.0
  json_annotation: ^4.8.1
  mongo_dart: ^0.10.1
  nyxx: ^6.2.1
  nyxx_commands: ^6.0.2
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.9
  http: ^1.1.0
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
